name: flutter_instagram_story
description: Sharing photos to Instagram story.
version: 0.0.2
homepage: https://github.com/dominikrudzki/flutter_instagram_story

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterInstagramStoryPlugin
